### PR TITLE
Create navbar and did some styling

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I created a simple navbar and added some styling. Now I will continue styling the log in and sign up pages.

Marcia

### CODE REVIEW

**Comment by ghost** [comment]
Hi.. update: if you click on Code Connection on navbar you are redirected to home page. I added the views to devise and I styled them a little bit.

Have  a good day!

**Comment by jemagee** [comment]
I like that someone took some initiative on the navbar, but I think there's some repeated code in here...in the application.html.erb you added links to bootstrap and jquery and I [i]believe[i] rails does that automatically through the asset pipeline since the bootstrap gem is installed.  If you boot up the application locally `rails s` and then look at the source code you'll see a lot of script src stuff.  I'm not really fully versed in the pipeline so if I'm wrong, please someone tell me?

**Comment by ghost** [comment]
Yes! you were right! I didn't need the extra code for bootstrap on the layout application.html.erb. I need to double check my past rails apps because I was doing that in all of them. Thanks for point that out!

**Comment by jemagee** [comment]
Not a problem

I’m not great with understanding the asset pipeline but my understanding is that if you include it in the pipelines (like bootstrap or jQuery) it’s automatically included in your app as well, it’s one of the benefits of rails - writing the code for you that makes up your foundation

**Comment by jemagee** [comment]
I did merge this commit, but not before I wrote some simple tests (that you can see in the features folder called logged_in_user_spec) to verify that the conditional formatting in the application was working.  I didn't want to be an ogre about it and require more test writing that i could do and fortunately git hub let me add it to the commit.

**Comment by ghost** [comment]
you are not an ogre :)

**Pull request merged**
