### PR TITLE
Welcome_mailer

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Hi. This is the first time I try to create a welcome email using devise so I'm not completely sure if what I did is right. I have been coding for about 4 months and this is the first time I contributed to an open source.. so a bit nervous :). I hope my contribution can help this project somehow.
Have a nice day!

Marcia

**Comment by jemagee** [comment]
Marcia

Thank you very much for this.  This is the first project I've ever had a pull request on, so I hope I do this right and don't turn you away.

I reviewed the code and I like having templates set up to work with in the future, but I didn't see any tests written.  I'm not looking for complex tests just some basics that implement that the function does work as intended.

i recently [wrote](http://www.mageeworld.com/articles/45) an article on my own learning with ActionMailer (which is pretty new) and I did create some basic tests that you can see [here](https://github.com/jemagee/johnsblog/commit/ee4774c1b8fc3dfe64899b7907f97770809c970e).  I didn't really write any fancy tests, I just used the email_spec gem to set up some basic testing.  

For any functionality added to the project I think it's good to have them tested, if that's ok, let me know what you think

**Comment by ghost** [comment]
Hi, 

So... I added the gem email_spec (never used before.. totally lost yesterday when you were talking about cucumbers :) ). Added a few tests. I was able to see the preview of the email on my terminal.. few things have to be fixed when name and login are added to the user (I commented out this parts in the email body). Also, I added content to the email template. I'm not a native English speaker so not sure if it's grammatically ok. Anyway, it is just an idea.

Have a good day, 

Marcia

**Comment by jemagee** [comment]
This pull request has been merged as well, I modified the rails_helper file a bit as there were a lot of requires at the top that weren't [i]required[/i].  The Email Spec can be added within the config block which is how I did it, and database cleaner is a useful gem, but I don't think we need its functionality just yet.  It can be tricky to work with sometimes especially when dealing with JS as well (and needed seed data, trust me) I also tweaked the tests and altered to email to include the root_url for future use

**Comment by ghost** [comment]
Super!
I saw the tests you made, I was a bit confuse about how to use FactoryGirl. Now it is much clear and good to have for future references +1:

**Pull request merged**
