### PR TITLE
Add username to Users

### PR DESCRIPTION
**Pull request by chuggingCoffee**
Hi,

I saw that you wanted to add a username field to devise users.

- Users can now add a username when creating an account, login with that username, and edit the username when updating their profile.

- Updated the devise views to include username where needed

- Added basic bootstrap styling on some forms.  Left basic so you can edit the styling as needed.

This is my first real pull request, so let me know if I need to change something.

Cheers,
Mike

### CODE REVIEW

**Comment by jemagee** [comment]
@pdxmike Thank you for this, and I've been reviewing it, and it seems to me like it should work, but I don't see any testing to verify that it would work?  Is that something you could add, in rspec?  I think a basic should matcher for the case insensitive uniqueness and an expansion of the signing up testing I started would be good.  (I realize I haven't done any 'required entry testing' yet

**Comment by chuggingCoffee** [comment]
No problem.  I'm still relatively new to testing, so I'll give it a go in the next few days when I'm free.  Question: should a username be REQUIRED, or should it be optional?  Not sure what the end goal is.

**Comment by jemagee** [comment]
Mike

It’s no problem, take your time, and if you need some guidance, please ask.  I’m mostly a newbie as well but have learned the TDD from the beginning, I’m not looking for in-depth tests yet, just the basics to make sure it works.

I think a user name should be required yes, but I didn’t even write tests to make sure that the email and password were entered properly so you could do that with just  a shoulda-matcher

The shoulda-matcher repository it outstanding in guiding you through how to use it easily.

**Comment by jemagee** [comment]
Mike

It’s no problem, take your time, and if you need some guidance, please ask.  I’m mostly a newbie as well but have learned the TDD from the beginning, I’m not looking for in-depth tests yet, just the basics to make sure it works.

I think a user name should be required yes, but I didn’t even write tests to make sure that the email and password were entered properly so you could do that with just  a shoulda-matcher

The [shoulda-matcher](https://github.com/thoughtbot/shoulda-matchers)  repository it outstanding in guiding you through how to use it easily.

**Comment by jemagee** [comment]
Pull request overridden by Pull Request #16 which integrated testing as well

**Pull request closed without merging**
